[env:heltec-mesh-node-t114-inkhud]
extends = nrf52840_base, inkhud
board = heltec_mesh_node_t114
board_check = true
debug_tool = jlink
build_flags = 
  ${nrf52840_base.build_flags}
  ${inkhud.build_flags}
  -I variants/heltec_mesh_node_t114_inkhud
  -L "${platformio.libdeps_dir}/${this.__env__}/bsec2/src/cortex-m4/fpv4-sp-d16-hard"
  -D DEBUG_HEAP
build_src_filter = 
  ${nrf52_base.build_src_filter} 
  ${inkhud.build_src_filter}
lib_deps = 
  ${inkhud.lib_deps} ; InkHUD libs first, so we get GFXRoot instead of AdafruitGFX
  ${nrf52840_base.lib_deps}
  lewisxhe/PCF8563_Library@^1.0.1